-- ========================================
-- Kwetu Garage — fichier d’aide (pas d’exécution automatique de CREATE DATABASE)
-- ========================================
--
-- PostgreSQL n’autorise pas CREATE DATABASE dans un bloc DO / transaction.
-- Utilisez plutôt :
--
--   Windows (PowerShell, depuis ce dossier « database ») :
--     $env:PGPASSWORD = "votre_mot_de_passe"
--     .\install-kwetu-garage.ps1
--
--   Ou manuellement :
--     psql -U postgres -d postgres -f 00-create-database.sql
--     psql -U postgres -d kwetu_garage -f schema.sql
--     psql -U postgres -d kwetu_garage -f seed.sql
--
--   Linux / macOS :
--     chmod +x install-kwetu-garage.sh
--     export PGPASSWORD=...
--     ./install-kwetu-garage.sh
--

SELECT 'Utilisez install-kwetu-garage.ps1 ou les commandes ci-dessus.' AS instruction;
